# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-09 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glav', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggs',
            name='opisanie',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
